### PR TITLE
This might be necessary.

### PR DESCRIPTION
**Pull request by k2b6s9j**
I used some ES6 syntax, that might need a transpilier reminder for Atom.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Hmm.. looks like it still is not working, should I do something more? Or maybe just use ES5 syntax?

**Comment by k2b6s9j** [comment]
Nah, ES6 is the future... :star2: This will be fine. I just didn't remember if that babel line is still needed. It doesn't hurt anything to have it there.

**Comment by k2b6s9j** [comment]
I'll give it a test in a bit.

**Comment by Krzysztof-Cieslak** [comment]
I've currently rollback to the ES5 syntax. If You test it and confirm it's working feel free to make new PR for it :)

**Pull request merged**
