### PR TITLE
Working dependency installation.

### PR DESCRIPTION
**Pull request by keplersj**
I've checked the syntax.
I've checked that it works.
I've tested locally.

It all installs and activates itself.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Hey, will it also add some kind of notification for user in UI ?

**Comment by k2b6s9j** [comment]
Yes! A notification with a progress bar, listing the package being
installed is shown.

**Comment by Krzysztof-Cieslak** [comment]
Thanks a lot :) Tested on my machine and it looks great!

**Comment by k2b6s9j** [comment]
Woot!

**Pull request merged**
